👨‍🏫 **Jupyter By:** Ahmad Ahmadi 

🌏 **[Website: izlearn.ir](https://izlearn.ir)**

🔗 **[More Links](#more-links)**

---

## NumPy

### What is NumPy? 

🔸 It stands for **Nu**merical **Py**thon.

🔸 In machine learning we have to convert all types of data into **series of numbers**. 

🔸 NumPy is essential package for **data analysis**

🔸 [Numpy Documentation](https://numpy.org/doc/2.1/user/absolute_beginners.html)

---

### Why NumPy?

🔸 It's **fast**.

🔸 Behind the scenes the optimization code was written in **C** language! (a very powerful & fast programming language)

🔸 NumPy supports techniques called **vectorization** and **broadcasting** that help us avoid using loops!

🔸 See image of [vectorization](Jupyter-Images/vectorization-&-broadcasting-in-numpy-01.png) and [broadcasting](Jupyter-Images/vectorization-&-broadcasting-in-numpy-02.png) in NumPy.

---

In [1]:
# import numpy package:
import numpy as np

### NumPy's DataTypes & Attributes

🔸 NumPy's main datatype is just **ndarray**,

🔸 **ndarray** means **n** dimensional array.

In [2]:
# Use np.array() to create an array in 'NumPy'
my_list = [5, 7, 10]
array1 = np.array(my_list)

In [3]:
# Return 'array1'
array1

array([ 5,  7, 10])

In [4]:
# Check the type of 'array1'
type(array1)

numpy.ndarray

In [7]:
# More arrays
array2 = np.array([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]])
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
array3 = np.array([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],
                   [[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]]])

array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

---
<a name='more-links'></a>
### THE END 

🔸 If you want to be in touch with **me** (Ahmad Ahmadi), click this [link](https://t.me/izlearn_support) to be taken to my **Telegram**.

🔸 If you have a **LinkedIn** account, [this](https://linkedin.com/in/ahmad-ahmadi95/) is my page I will be happy to have you as my connections.

🔸 Finally using this [link](https://zarinp.al/454855)(Iran) and this [link](https://paylink.payment4.com/fa/izlearn/2572d5b8-9ece-48ba-8014-3192ed9274e2)(out of Iran) you're able to **donate🎁** and **support** our team. 🤙🏼