## NumPy Exercises

🔸 In this jupyter notebook we'll provied you **41** exercises in **NumPy** library.

🔸 These exercises are directly taken from **quick introduction to NumPy notebook**.

👀 If you get stuck, try searching for question in the following format: `how to do SOMETHING with numpy` and **SOMETHING** is the function you want to use in NumPy.

🤝🏼 This jupyter notebook is designed by [Ahmad Ahmadi](https://www.linkedin.com/in/ahmad-ahmadi95/).

---

🔸 **Q1.** Import `NumPy` as its short name `np`.

🔹 **Answer**

In [1]:
import numpy as np

🔸 **Q2.** Create `one-dimensional` NumPy array using `np.array( )` function.

🔹 **Answer**

In [2]:
one_dim_array = np.array([1, 2, 3, 4, 5])

In [3]:
one_dim_array

array([1, 2, 3, 4, 5])

🔸 **Q3.** Create `two-dimensional` NumPy array using `np.array( )` function.

🔹 **Answer**

In [4]:
two_dim_array = np.array([[1.0, 2.0, 3.0],
                          [4.0, 5.0, 6.0]])

In [5]:
two_dim_array

array([[1., 2., 3.],
       [4., 5., 6.]])

🔸 **Q4.** Create `three-dimensional` NumPy array using `np.array( )` function.

🔹 **Answer**

In [6]:
three_dim_array = np.array([[[1, 2],
                            [3, 4]],
                            [[5, 6],
                            [7, 8]]])

In [7]:
three_dim_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

🙋🏽‍♂️ We've created **three different arrays**; `one_dim_array`, `two_dim_array`, `three_dim_array`.

🔸 **Q5.** Find the **shape**, **number of dimensions**, **data type**, **size** and **type** of each array.

🔹 **Answer**

In [8]:
print(f"Shape of one_dim_array: {one_dim_array.shape}")
print(f"Shape of two_dim_array: {two_dim_array.shape}")
print(f"Shape of three_dim_array: {three_dim_array.shape}")
print('------')
print(f"ndim of one_dim_array: {one_dim_array.ndim}")
print(f"ndim of two_dim_array: {two_dim_array.ndim}")
print(f"ndim of three_dim_array: {three_dim_array.ndim}")
print(f"------")
print(f"data types of one_dim_array: {one_dim_array.dtype}")
print(f"data types of two_dim_array: {two_dim_array.dtype}")
print(f"data types of three_dim_array: {three_dim_array.dtype}")
print(f"------")
print(f"size of one_dim_array: {one_dim_array.size}")
print(f"size of two_dim_array: {two_dim_array.size}")
print(f"size of three_dim_array: {three_dim_array.size}")
print(f"------")
print(f"type of one_dim_array: {type(one_dim_array)}")
print(f"type of two_dim_array: {type(two_dim_array)}")
print(f"type of three_dim-array: {type(three_dim_array)}")

Shape of one_dim_array: (5,)
Shape of two_dim_array: (2, 3)
Shape of three_dim_array: (2, 2, 2)
------
ndim of one_dim_array: 1
ndim of two_dim_array: 2
ndim of three_dim_array: 3
------
data types of one_dim_array: int64
data types of two_dim_array: float64
data types of three_dim_array: int64
------
size of one_dim_array: 5
size of two_dim_array: 6
size of three_dim_array: 8
------
type of one_dim_array: <class 'numpy.ndarray'>
type of two_dim_array: <class 'numpy.ndarray'>
type of three_dim-array: <class 'numpy.ndarray'>


🔸 **Q6.** Import `Pandas` and create a **DataFrame** out of `two_dim_array` you've created.

🔹 **Answer** 

In [9]:
import pandas as pd

In [10]:
my_df = pd.DataFrame(data=two_dim_array)

In [11]:
my_df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

🔸 **Q7.** Create an array of shape **(10, 2)** with only **ones**.

🔹 **Answer**

In [12]:
ones = np.ones(shape=(10, 2))

In [13]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

🔸 **Q8.** Create an array of shape **(7, 2, 3)** of only **zeros**.

🔹 **Answer**

In [14]:
zeros = np.zeros(shape=(7, 2, 3))

In [15]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

🔸 **Q9.** Create an array within a range of **0** and **100** with **step 3**.

🔹 **Answer**

In [16]:
my_array1 = np.arange(0, 100, 3)

In [17]:
my_array1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

🔸 **Q10.** Create an array with **20** evenly spaced numbers between **1** and **100**.

🔹 **Answer**

In [18]:
my_array2 = np.linspace(start=1, stop=100, num=20)

In [19]:
my_array2

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

🔸**Q11.** Create a **random** array with numbers between **0** and **10** of size **(7, 2)**.

🔹 **Answer**

In [20]:
random_array1 = np.random.randint(low=0, high=10, size=(7, 2))

In [21]:
random_array1

array([[0, 8],
       [6, 4],
       [8, 8],
       [0, 2],
       [4, 2],
       [2, 4],
       [6, 1]], dtype=int32)

🔸**Q12.** Create a **random** array of **floats** between **0** and **1** of shape **(3, 5)**.

🔹**Answer**

In [22]:
random_array2 = np.random.random(size=(3, 5))

In [23]:
random_array2

array([[0.22309141, 0.30772857, 0.17281966, 0.93049652, 0.91608744],
       [0.64540696, 0.83609508, 0.30715255, 0.92084592, 0.31689135],
       [0.64110941, 0.73672447, 0.28828802, 0.59015186, 0.5359996 ]])

---

💡 Set the **random seed** to **7**.

---

🔸 **Q13.** Create a **random** array of numbers between **0** & **10** of **size (4, 6)**

🔹 **Answer**

In [24]:
np.random.seed(seed=42)
random_array3 = np.random.randint(low=0, high=10, size=(4, 6))

In [25]:
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

🔸 **Q14.** Create a random of numbers between **1** & **10** of **size (3, 7)** then save it to a variable (for example `random_array4`).

🔸 Finally, find **the number of unique numbers** within that array.

🔹**Answer**

In [26]:
random_array4 = np.random.randint(low=1, high=10, size=(3, 7))
print(f"The unique numbers in random_array4 is {np.unique(random_array4)}")

The unique numbers in random_array4 is [1 2 3 4 5 7 9]


In [27]:
random_array4

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]], dtype=int32)

🔸 **Q15.** Find the value at index of **0** of `random_array4` you've just created.

🔹 **Answer**

In [28]:
random_array4[0]

array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

🔸 **Q16.** Get the **first 2 rows** of `random_array4` you've just created.

🔹 **Answer**

In [29]:
random_array4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

🔸 **Q17.** Get the **first 2 values** of the **first 2 rows** of the `random_array4`.

🔹 **Answer**

In [30]:
random_array4[:2, :2]

array([[9, 1],
       [5, 3]], dtype=int32)

🔸 **Q18.** Create a **random** array of numbers between **0** and **10**, then create an array of **ones**.

🔸 The sizes of **both arrays** is **(4, 6)**. 

🔸 Save them into variables (`random_array5` and `ones`) 

🔹**Answer**

In [31]:
random_array5 = np.random.randint(low=0, high=10, size=(4, 6))
ones = np.ones(shape=(4, 6))

In [32]:
random_array5

array([[6, 7, 2, 0, 3, 1],
       [7, 3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1, 9],
       [3, 7, 6, 8, 7, 4]], dtype=int32)

In [33]:
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

🔸 **Q19.** Add `random_array5` and `ones` together.

In [34]:
random_array5 + ones

array([[ 7.,  8.,  3.,  1.,  4.,  2.],
       [ 8.,  4.,  2.,  6.,  6., 10.],
       [ 4.,  6.,  2., 10.,  2., 10.],
       [ 4.,  8.,  7.,  9.,  8.,  5.]])

🔸 **Q20.** Create another array of **ones** (shape of **(6, 4)**) and try to **add** this `new_ones` array to `random_array5`.

In [35]:
new_ones = np.ones(shape=(6, 4))
random_array5 + new_ones

ValueError: operands could not be broadcast together with shapes (4,6) (6,4) 

---

👀 When you run the previous cell, It produces the **ValueError**.

---

🔸 **Q21.** Subtract `ones` array from `random_array5` array.

🔹 **Answer**

In [36]:
random_array5 - ones

array([[ 5.,  6.,  1., -1.,  2.,  0.],
       [ 6.,  2.,  0.,  4.,  4.,  8.],
       [ 2.,  4.,  0.,  8.,  0.,  8.],
       [ 2.,  6.,  5.,  7.,  6.,  3.]])

🔸 **Q22.** Multiply the `random_array5` by `ones` array.

🔹 **Answer** 

In [37]:
# Method one -> using *
random_array5 * ones

array([[6., 7., 2., 0., 3., 1.],
       [7., 3., 1., 5., 5., 9.],
       [3., 5., 1., 9., 1., 9.],
       [3., 7., 6., 8., 7., 4.]])

In [38]:
# Methods two -> using np.multiply()
np.multiply(random_array5, ones)

array([[6., 7., 2., 0., 3., 1.],
       [7., 3., 1., 5., 5., 9.],
       [3., 5., 1., 9., 1., 9.],
       [3., 7., 6., 8., 7., 4.]])

🔸 **Q23.** Take `random_array5` to the power of **2**.

In [39]:
# Method one -> using **
random_array5 ** 2

array([[36, 49,  4,  0,  9,  1],
       [49,  9,  1, 25, 25, 81],
       [ 9, 25,  1, 81,  1, 81],
       [ 9, 49, 36, 64, 49, 16]], dtype=int32)

In [40]:
# Method two -> using np.square()
np.square(random_array5)

array([[36, 49,  4,  0,  9,  1],
       [49,  9,  1, 25, 25, 81],
       [ 9, 25,  1, 81,  1, 81],
       [ 9, 49, 36, 64, 49, 16]], dtype=int32)

🔸 **Q24.** Calculate the **mean** of `random_array5`.

🔹 **Answer**

In [41]:
# Method one -> np.mean()
np.mean(random_array5)

np.float64(4.666666666666667)

In [42]:
# Method two -> your_array.mean()
random_array5.mean()

np.float64(4.666666666666667)

🔸 **Q25.** Calculate the **maximum** value of `random_array5`.

🔹 **Answer**

In [43]:
# Method one -> np.max()
np.max(random_array5)

np.int32(9)

In [44]:
# Method two -> your_array.max()
random_array5.max()

np.int32(9)

🔸 **Q26.** Calculate the **minimum** value of `random_array5`.

🔹 **Answer**

In [45]:
# Method one -> np.min()
np.min(random_array5)

np.int32(0)

In [46]:
# Method two -> your_array.min()
random_array5.min()

np.int32(0)

🔸 **Q27.** Calculate the **standard deviation** of `random_array5`. 

🔹 **Answer**

In [47]:
# Method one -> np.std()
np.std(random_array5)

np.float64(2.7938424357067015)

In [48]:
# Method two -> your_array.std()
random_array5.std()

np.float64(2.7938424357067015)

🔸 **Q28.** Find the **variance** of the `random_array5`.

🔹 **Answer**

In [49]:
# Method one -> np.var()
np.var(random_array5)

np.float64(7.8055555555555545)

In [50]:
# Method two -> your_array.var()
random_array5.var()

np.float64(7.8055555555555545)

🔸 **29.** Reshape the `random_array5` to **(3, 8, 1)**

🔹 **Answer**

In [51]:
# Method one -> np.reshape()
np.reshape(random_array5, newshape=(3, 8, 1))

array([[[6],
        [7],
        [2],
        [0],
        [3],
        [1],
        [7],
        [3]],

       [[1],
        [5],
        [5],
        [9],
        [3],
        [5],
        [1],
        [9]],

       [[1],
        [9],
        [3],
        [7],
        [6],
        [8],
        [7],
        [4]]], dtype=int32)

In [52]:
# Method two -> your_array.reshape()
random_array5.reshape((3, 8, 1))

array([[[6],
        [7],
        [2],
        [0],
        [3],
        [1],
        [7],
        [3]],

       [[1],
        [5],
        [5],
        [9],
        [3],
        [5],
        [1],
        [9]],

       [[1],
        [9],
        [3],
        [7],
        [6],
        [8],
        [7],
        [4]]], dtype=int32)

🔸 **Q30.** Transpose `random_array5`.

In [53]:
# Method one -> np.transpose()
np.transpose(random_array5)

array([[6, 7, 3, 3],
       [7, 3, 5, 7],
       [2, 1, 1, 6],
       [0, 5, 9, 8],
       [3, 5, 1, 7],
       [1, 9, 9, 4]], dtype=int32)

In [54]:
# Method two -> your_array.T
random_array5.T

array([[6, 7, 3, 3],
       [7, 3, 5, 7],
       [2, 1, 1, 6],
       [0, 5, 9, 8],
       [3, 5, 1, 7],
       [1, 9, 9, 4]], dtype=int32)

🔸 **Q31.** Create two arrays of **random integers** between **0** to **10**. 

🔸 one of size **(2, 3)** and  the other of size **(4, 3)**

🔹 **Answer** 

In [55]:
random_int1 = np.random.randint(low=0, high=10, size=(2, 3))
random_int2 = np.random.randint(low=0, high=10, size=(4, 3))

In [56]:
random_int1

array([[1, 4, 7],
       [9, 8, 8]], dtype=int32)

In [57]:
random_int2

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2],
       [0, 7, 2]], dtype=int32)

🔸 **Q32.** Perform a **dot product** on the `random_int1` and `random_int2`. 

🔹 **Answer** 

In [58]:
np.dot(random_int1, random_int2)

ValueError: shapes (2,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

---

👀 When you run the previous cell, It produces the **ValueError**. 

---

🔸 **Q33.** Try fix the previous error using **transpose of one of the arrays**. 

🔹 **Answer**

In [59]:
np.dot(random_int1, random_int2.T)

array([[ 74,  36,  49,  42],
       [112, 128, 135,  72]], dtype=int32)

👀 Why this works now? 

🔗 Check out this [link]() to the **documentation of np.dot( )** as well as this [link](https://www.mathsisfun.com/algebra/vectors-dot-product.html) from **Math is fun**. 

🔸 **Q34.** Create two arrays of **random integers** between **0** and **10** of the **same** size. 

🔸 Save them into different variables.

🔸 Finally compare them using **>** operator.

🔹 **Answer**

In [60]:
random_int1 = np.random.randint(low=0, high=10, size=(3, 5))
random_int2 = np.random.randint(low=0, high=10, size=(3, 5))

In [61]:
random_int1

array([[2, 0, 4, 9, 6],
       [9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7]], dtype=int32)

In [62]:
random_int2

array([[4, 2, 7, 5, 2],
       [0, 2, 4, 2, 0],
       [4, 9, 6, 6, 8]], dtype=int32)

In [63]:
# Compare here
random_int1 > random_int2

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

🔸 **Q35.** Compare the two previous arrays using **>=**. 

🔹 **Answer**

In [64]:
random_int1 >= random_int2

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True, False]])

🔸 **Q36.** Find which elements of the **first** array are greater than **5**. 

🔹 **Answer**

In [65]:
random_int1 > 5

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True]])

🔸 **Q37.** Which parts of each array are **equal**? 

🔹 **Answer**

In [66]:
random_int1 == random_int2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False]])

🔸 **Q38.** Sort `random_int1` that you newly created.

🔹 **Answer**

In [67]:
random_int1.sort()

In [68]:
random_int1

array([[0, 2, 4, 6, 9],
       [6, 7, 8, 8, 9],
       [0, 1, 6, 6, 7]], dtype=int32)

🔸 **Q39.** Sort the **indices** of `random_int1` that you newly created

🔹 **Answer**

In [69]:
random_int1.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

🔸 **Q40.** Find the **index** of **maximum** value in `random_int2` array.

🔹 **Answer**

In [70]:
np.argmax(random_int2)

np.int64(11)

🔸 **Q41.** Find the **index** of **minimum** value in `random_int2` array.

🔹 **Answer** 

In [71]:
np.argmin(random_int1)

np.int64(0)

---

### More Resources

🔗 For more  exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html).

🔗 For more helpful materials, check out the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Most of the time as you reading the questions you can find usefull functions to learn.

👀 Finally, remeber that the best way to learn something new is **to try it**. 

---
<a name='support-me'></a>
### THE END 

🔸 If you want to be in touch with **me** (Ahmad Ahmadi), click this [link](https://t.me/izlearn_support) to be taken to my **Telegram**.

🔸 If you have a **LinkedIn** account, **[this](https://linkedin.com/in/ahmad-ahmadi95/)** is my page I will be happy to have you as my connections.

🔸 Finally using this **[link](https://zarinp.al/454855)**(Iran) and this **[link](https://paylink.payment4.com/fa/izlearn/2572d5b8-9ece-48ba-8014-3192ed9274e2)**(out of Iran) you're able to **donate🎁** and **support** our team. 🤙🏼